US9Task16 add UI for quiz title
SER516-S19/project3-team9 pull request #6
Opened 2019-04-03 04:49 UTC by xiangweizheng

US9Task16 add UI for quiz title

2019-04-04 11:40 UTC, sverma23x requested changes

2019-04-04 11:40 UTC, ShivamVerma920302 commented on src/view/ProfTitleView.java
> +
Please remove these blank spaces between the curly braces.

2019-04-06 07:38 UTC, sverma23x approved these changes

2019-04-10 23:58 UTC, rubyqzhao reviewed
You need to resolve the merge conflicts before this can move forward.

2019-04-11 01:37 UTC, closed without merging

2019-04-11 01:37 UTC, xiangweizheng commented
This pull is outdated.